import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Bot, CheckCircle2, Copy, Plus, RefreshCw, Trash2, TrendingDown, TrendingUp, WalletCards } from "lucide-react";
import { useState } from "react";
import toast from "react-hot-toast";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api, { getApiError } from "../api";
import type { AnalyticsData, BudgetStatus, Category, RecurringTransaction, TelegramStatus } from "../types";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const palette = ["#7559e8", "#14b8a6", "#f59e0b", "#f43f5e", "#3b82f6", "#d946ef", "#64748b"];
const now = new Date();
const today = () => new Date().toISOString().slice(0, 10);

export function ViewHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <header className="mb-8"><p className="text-xs font-bold tracking-[.18em] text-brand-600">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold tracking-tight">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{description}</p></header>;
}

export function AnalyticsView() {
  const query = useQuery({ queryKey: ["analytics"], queryFn: async () => (await api.get<AnalyticsData>("/analytics", { params: { months: 6 } })).data });
  const data = query.data;
  const change = data?.month_change_percent;
  if (query.isLoading) return <Loading />;
  if (query.isError || !data) return <ErrorState retry={() => query.refetch()} />;
  return <><ViewHeader eyebrow="ANALYTICS" title="Understand your spending" description="See how your expenses change over time and which categories have the greatest impact." />
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="This month" value={currency.format(data.current_month)} /><Metric label="Last month" value={currency.format(data.previous_month)} /><Metric label="Monthly change" value={change == null ? "No comparison" : `${Math.abs(change).toFixed(1)}%`} icon={change != null && change > 0 ? <TrendingUp className="text-red-500" /> : <TrendingDown className="text-emerald-500" />} /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><article className="surface h-[360px] p-5 sm:p-6"><h2 className="font-bold">Six-month trend</h2><p className="mb-5 mt-1 text-xs text-slate-400">Total spending per month</p><ResponsiveContainer width="100%" height="82%"><AreaChart data={data.trend}><defs><linearGradient id="trend" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#7559e8" stopOpacity={0.35}/><stop offset="95%" stopColor="#7559e8" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="label" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false} tickFormatter={(v: number)=>`₹${v/1000}k`}/><Tooltip formatter={(value)=>currency.format(Number(value))}/><Area type="monotone" dataKey="total" stroke="#7559e8" strokeWidth={3} fill="url(#trend)"/></AreaChart></ResponsiveContainer></article>
    <article className="surface h-[360px] p-5 sm:p-6"><h2 className="font-bold">Category share</h2><p className="mt-1 text-xs text-slate-400">Last six months</p>{data.categories.length ? <><ResponsiveContainer width="100%" height="65%"><PieChart><Pie data={data.categories} dataKey="total" nameKey="category" innerRadius={58} outerRadius={88} paddingAngle={3}>{data.categories.map((item, index)=><Cell key={item.category} fill={palette[index%palette.length]}/>)}</Pie><Tooltip formatter={(value)=>currency.format(Number(value))}/></PieChart></ResponsiveContainer><div className="flex flex-wrap justify-center gap-x-4 gap-y-2">{data.categories.slice(0,5).map((item,index)=><span className="flex items-center gap-1.5 text-[11px] text-slate-500" key={item.category}><i className="h-2 w-2 rounded-full" style={{background:palette[index%palette.length]}}/>{item.category}</span>)}</div></> : <Empty text="Analytics will appear after you add expenses."/>}</article></section>
  </>;
}

export function BudgetsView({ categories }: { categories: Category[] }) {
  const client = useQueryClient();
  const [month, setMonth] = useState(now.getMonth()+1); const [year, setYear] = useState(now.getFullYear()); const [category, setCategory] = useState("__overall"); const [limit, setLimit] = useState("");
  const query = useQuery({ queryKey:["budgets",month,year], queryFn:async()=>(await api.get<BudgetStatus[]>("/budgets/status",{params:{month,year}})).data });
  const save = useMutation({mutationFn:()=>api.post("/budgets",{category:category==="__overall"?null:category,limit_amount:Number(limit),month,year}),onSuccess:async()=>{await client.invalidateQueries({queryKey:["budgets"]});setLimit("");toast.success("Budget saved")},onError:(e)=>toast.error(getApiError(e))});
  const remove = useMutation({mutationFn:(id:number)=>api.delete(`/budgets/${id}`),onSuccess:async()=>{await client.invalidateQueries({queryKey:["budgets"]});toast.success("Budget removed")}});
  return <><ViewHeader eyebrow="BUDGETS" title="Plan before you spend" description="Set an overall monthly target or create category limits. Progress updates automatically from your expenses." />
    <section className="surface mb-5 p-5"><form className="grid gap-3 md:grid-cols-[1fr_1fr_120px_120px_auto]" onSubmit={(e)=>{e.preventDefault();if(Number(limit)>0)save.mutate()}}><select className="field py-2.5" value={category} onChange={e=>setCategory(e.target.value)}><option value="__overall">Overall budget</option>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select><input className="field py-2.5" type="number" min="1" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="Limit amount" required/><select className="field py-2.5" value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{new Date(2026,i).toLocaleString("en",{month:"short"})}</option>)}</select><input className="field py-2.5" type="number" min="2020" max="2100" value={year} onChange={e=>setYear(Number(e.target.value))}/><button className="rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-brand-700" disabled={save.isPending}>Save</button></form></section>
    {query.isLoading?<Loading/>:query.data?.length?<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data.map(item=><article className="surface p-5" key={item.id}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{item.category??"Overall"}</p><strong className="mt-2 block text-xl">{currency.format(item.spent)} <small className="font-normal text-slate-400">of {currency.format(item.limit_amount)}</small></strong></div><button className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={()=>remove.mutate(item.id)}><Trash2 size={16}/></button></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.percentage>100?"bg-red-500":item.percentage>80?"bg-amber-500":"bg-brand-500"}`} style={{width:`${Math.min(item.percentage,100)}%`}}/></div><div className="mt-2 flex justify-between text-xs"><span className={item.percentage>100?"font-bold text-red-600":"text-slate-400"}>{item.percentage}% used</span><span className="text-slate-400">{item.remaining>=0?`${currency.format(item.remaining)} left`:`${currency.format(Math.abs(item.remaining))} over`}</span></div></article>)}</section>:<Empty text="No budgets for this period. Set one above to start tracking progress."/>}
  </>;
}

export function RecurringView({ categories }: { categories: Category[] }) {
  const client=useQueryClient(); const [showForm,setShowForm]=useState(false); const [description,setDescription]=useState("");const [amount,setAmount]=useState("");const [category,setCategory]=useState(categories[0]?.name??"Other");const [frequency,setFrequency]=useState<"weekly"|"monthly">("monthly");const [nextDate,setNextDate]=useState(today());
  const query=useQuery({queryKey:["recurring"],queryFn:async()=>(await api.get<RecurringTransaction[]>("/recurring")).data});
  const create=useMutation({mutationFn:()=>api.post("/recurring",{description,amount:Number(amount),category,frequency,next_run_date:nextDate}),onSuccess:async()=>{await client.invalidateQueries({queryKey:["recurring"]});await client.invalidateQueries({queryKey:["expenses"]});setShowForm(false);setDescription("");setAmount("");toast.success("Recurring expense created")},onError:e=>toast.error(getApiError(e))});
  const update=useMutation({mutationFn:(item:RecurringTransaction)=>api.put(`/recurring/${item.id}`,{description:item.description,amount:item.amount,category:item.category,frequency:item.frequency,next_run_date:item.next_run_date,active:!item.active}),onSuccess:()=>client.invalidateQueries({queryKey:["recurring"]})});
  const remove=useMutation({mutationFn:(id:number)=>api.delete(`/recurring/${id}`),onSuccess:()=>client.invalidateQueries({queryKey:["recurring"]})});
  return <><div className="flex items-start justify-between gap-4"><ViewHeader eyebrow="AUTOMATION" title="Recurring transactions" description="Schedule rent, subscriptions, and regular bills. Due transactions are created automatically when you open the app."/><button className="flex shrink-0 items-center gap-2 rounded-xl bg-brand-600 px-4 py-3 text-sm font-bold text-white" onClick={()=>setShowForm(v=>!v)}><Plus size={17}/>Add schedule</button></div>
    {showForm&&<form className="surface mb-5 grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-[1.3fr_.8fr_1fr_.8fr_1fr_auto]" onSubmit={e=>{e.preventDefault();create.mutate()}}><input className="field py-2.5" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)} required/><input className="field py-2.5" type="number" min="1" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)} required/><select className="field py-2.5" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c.id}>{c.name}</option>)}</select><select className="field py-2.5" value={frequency} onChange={e=>setFrequency(e.target.value as "weekly"|"monthly")}><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><input className="field py-2.5" type="date" value={nextDate} onChange={e=>setNextDate(e.target.value)} required/><button className="rounded-xl bg-brand-600 px-4 text-sm font-bold text-white" disabled={create.isPending}>Create</button></form>}
    {query.isLoading?<Loading/>:query.data?.length?<section className="surface divide-y divide-slate-100 overflow-hidden">{query.data.map(item=><div className="grid gap-4 p-5 sm:grid-cols-[44px_1fr_auto_auto] sm:items-center" key={item.id}><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-600"><RefreshCw size={19}/></span><div><p className="font-bold">{item.description}</p><p className="mt-1 text-xs text-slate-400">{item.category} · {item.frequency} · Next: {new Date(item.next_run_date+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</p></div><strong>{currency.format(item.amount)}</strong><div className="flex gap-1"><button className={`rounded-lg px-3 py-2 text-xs font-bold ${item.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`} onClick={()=>update.mutate(item)}>{item.active?"Active":"Paused"}</button><button className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={()=>remove.mutate(item.id)}><Trash2 size={16}/></button></div></div>)}</section>:<Empty text="No recurring transactions. Add rent, subscriptions, or regular bills to automate them."/>}
  </>;
}

export function TelegramView() {
  const client=useQueryClient();const [code,setCode]=useState<string|null>(null);
  const query=useQuery({queryKey:["telegram-status"],queryFn:async()=>(await api.get<TelegramStatus>("/telegram/status")).data,refetchInterval:code?5000:false});
  const generate=useMutation({mutationFn:async()=>(await api.post<{code:string}>("/telegram/generate-link-code")).data,onSuccess:data=>setCode(data.code),onError:e=>toast.error(getApiError(e))});
  const unlink=useMutation({mutationFn:()=>api.delete("/telegram/unlink"),onSuccess:async()=>{setCode(null);await client.invalidateQueries({queryKey:["telegram-status"]});toast.success("Telegram unlinked")}});
  return <><ViewHeader eyebrow="TELEGRAM BOT" title="Log expenses from chat" description="Link your Telegram account and add expenses without opening the web app."/><section className="mx-auto grid max-w-4xl gap-5 lg:grid-cols-[1fr_1.15fr]"><article className="surface p-6"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-sky-50 text-sky-600"><Bot size={28}/></span><h2 className="mt-5 text-xl font-bold">Connection status</h2>{query.data?.linked?<div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><p className="flex items-center gap-2 font-bold"><CheckCircle2 size={18}/>Telegram connected</p><p className="mt-1 text-xs opacity-70">Chat ID: {query.data.chat_id}</p><button className="mt-4 font-bold underline" onClick={()=>unlink.mutate()}>Unlink account</button></div>:<><p className="mt-2 text-sm leading-6 text-slate-500">Generate a temporary code, then send it to your bot using <b>/link CODE</b>.</p>{code?<div className="mt-5 rounded-xl border border-brand-200 bg-brand-50 p-5 text-center"><p className="text-xs font-bold tracking-widest text-brand-600">LINK CODE</p><strong className="mt-2 block text-3xl tracking-[.25em] text-brand-700">{code}</strong><button className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-brand-600" onClick={()=>{navigator.clipboard.writeText(code);toast.success("Code copied")}}><Copy size={13}/>Copy code</button><p className="mt-3 text-[11px] text-slate-400">Expires in 10 minutes</p></div>:<button className="mt-5 w-full rounded-xl bg-brand-600 px-4 py-3 text-sm font-bold text-white" onClick={()=>generate.mutate()} disabled={generate.isPending}>Generate link code</button>}</>}</article>
    <article className="surface p-6"><h2 className="text-lg font-bold">What you can say</h2><div className="mt-5 space-y-3">{[["Natural language","spent 500 on groceries yesterday"],["Direct command","/add 250 Food lunch"],["Recent expenses","/list"],["Monthly total","/summary"],["Budget status","/budget"]].map(([label,command])=><div className="rounded-xl bg-slate-50 p-3" key={command}><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{label}</p><code className="mt-1 block text-sm font-semibold text-slate-700">{command}</code></div>)}</div><div className="mt-5 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800"><AlertTriangle className="mt-0.5 shrink-0" size={16}/>The backend must have TELEGRAM_BOT_TOKEN configured and a public HTTPS webhook registered with Telegram.</div></article></section></>;
}

function Metric({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return <article className="surface p-5"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">{label}</p>{icon&&<span className="[&>svg]:h-5 [&>svg]:w-5">{icon}</span>}</div><strong className="mt-3 block text-2xl">{value}</strong></article>}
function Loading(){return <div className="grid gap-4 sm:grid-cols-3">{[1,2,3].map(i=><div className="h-32 animate-pulse rounded-2xl bg-slate-200" key={i}/>)}</div>}
function Empty({text}:{text:string}){return <div className="surface grid min-h-64 place-content-center p-8 text-center"><WalletCards className="mx-auto text-brand-500"/><p className="mt-3 max-w-sm text-sm text-slate-500">{text}</p></div>}
function ErrorState({retry}:{retry:()=>void}){return <div className="surface grid min-h-64 place-content-center text-center"><p className="text-sm text-red-600">Could not load this section.</p><button className="mt-2 text-sm font-bold text-brand-600" onClick={retry}>Try again</button></div>}
